CREATE DATABASE films;

CREATE TABLE films.PEOPLE (
                PEO_ID INT(3) NOT NULL,
                PEO_NAME CHAR(25) NOT NULL,
                PRIMARY KEY (PEO_ID)
);

ALTER TABLE films.PEOPLE COMMENT '';


CREATE TABLE films.GENRES (
                GEN_ID INT(2) NOT NULL,
                GEN_DESCRIPTION CHAR(25) NOT NULL,
                PRIMARY KEY (GEN_ID)
);

ALTER TABLE films.GENRES COMMENT '';


CREATE TABLE films.FILMS (
                FILM_ID INT(3) NOT NULL,
                NAME CHAR(30) NOT NULL,
                YEAR INT(4) NOT NULL,
                PRIMARY KEY (FILM_ID)
);

ALTER TABLE films.FILMS COMMENT '';


CREATE TABLE films.REL_GENRES_FILM (
                FILM_ID INT(3) NOT NULL,
                GEN_ID INT(2) NOT NULL
);

ALTER TABLE films.REL_GENRES_FILM COMMENT '';


CREATE TABLE films.REL_PEOPLE_FILM (
                ROLE CHAR(10) NOT NULL,
                PEO_ID INT(3) NOT NULL,
                FILM_ID INT(3) NOT NULL
);

ALTER TABLE films.REL_PEOPLE_FILM COMMENT '';


ALTER TABLE films.REL_PEOPLE_FILM ADD CONSTRAINT people_rel_people_film_fk
FOREIGN KEY (PEO_ID)
REFERENCES films.PEOPLE (PEO_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE films.REL_GENRES_FILM ADD CONSTRAINT genres_rel_genres_film_fk
FOREIGN KEY (GEN_ID)
REFERENCES films.GENRES (GEN_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE films.REL_PEOPLE_FILM ADD CONSTRAINT films_rel_people_film_fk
FOREIGN KEY (FILM_ID)
REFERENCES films.FILMS (FILM_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE films.REL_GENRES_FILM ADD CONSTRAINT films_rel_genres_film_fk
FOREIGN KEY (FILM_ID)
REFERENCES films.FILMS (FILM_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;