use js;
update products set pro_theme="Caribbean" where pro_code = "JUMBO101" and man_code="JUM";
update products set pro_theme="Fantasy" where pro_code = "JUMBO104" and man_code="JUM";
update products set pro_theme="Disney" where pro_code = "JUMBO107" and man_code="JUM";
update products set pro_theme="Cats" where pro_code = "JUMBO109" and man_code="JUM";
update products set pro_theme="Flowers and Gardens" where pro_code = "JUMBO113" and man_code="JUM";
update products set pro_theme="Fantasy" where pro_code = "JUMBO114" and man_code="JUM";
update products set pro_theme="Food and Drink" where pro_code = "JUMBO115" and man_code="JUM";
update products set pro_theme="Cats" where pro_code = "JUMBO116" and man_code="JUM";
update products set pro_theme="Landscapes" where pro_code = "JUMBO120" and man_code="JUM";
update products set pro_theme="Fantasy" where pro_code = "JUMBO121" and man_code="JUM";
update products set pro_theme="Comedy/Cartoon" where pro_code = "JUMBO123" and man_code="JUM";
update products set pro_theme="Fantasy" where pro_code = "JUMBO126" and man_code="JUM";
update products set pro_theme="Christmas" where pro_code = "JUMBO128" and man_code="JUM";
update products set pro_theme="Comedy/Cartoon" where pro_code = "JUMBO132" and man_code="JUM";
update products set pro_theme="Comedy/Cartoon" where pro_code = "JUMBO133" and man_code="JUM";
update products set pro_theme="Dogs" where pro_code = "JUMBO134" and man_code="JUM";
update products set pro_theme="Comedy/Cartoon" where pro_code = "JUMBO136" and man_code="JUM";
update products set pro_theme="Comedy/Cartoon" where pro_code = "JUMBO137" and man_code="JUM";
update products set pro_theme="World" where pro_code = "JUMBO138" and man_code="JUM";
update products set pro_theme="Comedy/Cartoon" where pro_code = "JUMBO141" and man_code="JUM";
